services:
  bot:
    image: sebaofficial/truthordarerobot:latest
    ports:
      - '3000:3000'
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    volumes:
      - ./db:/bot/prisma/db
    env_file:
      - .env
    restart: 'unless-stopped'
    depends_on:
      - migrate

  migrate:
    image: sebaofficial/truthordarerobot:latest
    command: pnpm install --frozen-lockfile && pnpm prisma migrate deploy
    env_file: '.env'
    labels:
      - 'com.centurylinklabs.watchtower.enable=true'
    restart: 'no'


  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --http-api-update --label-enable --cleanup
    env_file: '.env'
    labels:
      - 'com.centurylinklabs.watchtower.enable=false'
    ports:
      - '8080:8080'
    restart: unless-stopped
    depends_on:
      - bot

